### ISSUE TITLE
Access to app environment variable

### ISSUE THREAD

**Issue by Kikobeats** [fteychene/dokku-build-hook#2]
Could be possible access to env variables inside shell script?

Like:

```bash
echo "Loading ssh" && ssh-add <(echo "$SSH_PRIVATE_KEY")
```

It this currently is possible I will make a PR for udpate the README 😄

**Comment by fteychene** [comment]
Added in f81ddb06c6735d287a39e25e9c9503b4f3c32b8f commit
You can update the plugin if you still need this

Sory for the long time response
